### ISSUE TITLE
samples

### ISSUE THREAD

**Issue by DamDam123** [zheLim/auto-face-parsing#2]
Hello, can you put some examples, i want to see the effect,thank you very much!

**Comment by zheLim** [comment]
@DamDam123 Hi, this project is still under developing. The progress is slow since I only work on this when I am free

**Comment by zheLim** [comment]
@DamDam123 Hi, I am glad to inform you then the first demo video is uploaded!
You can view it on https://youtu.be/Yd077zcvm1A.
Thanks for your attention!
